<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQdnkAn5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQdnkAn5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQdnkAn5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQdnkAn5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQdnkAn5\App_KernelDevDebugContainer([
    'container.build_hash' => 'QdnkAn5',
    'container.build_id' => '92528347',
    'container.build_time' => 1678873518,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQdnkAn5');
