<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSIwiwBv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSIwiwBv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSIwiwBv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSIwiwBv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSIwiwBv\App_KernelDevDebugContainer([
    'container.build_hash' => 'SIwiwBv',
    'container.build_id' => 'cefca4e8',
    'container.build_time' => 1681309063,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSIwiwBv');
